server.port=1998
spring.application.name=account-management

# data source settings
spring.datasource.url=jdbc:mysql://localhost:3306/maktabatic?serverTimezone=UTC
spring.datasource.username=makataba-tic
spring.datasource.password=admin

# show or not the log for each sql query
spring.jpa.show-sql=true

# Hibernate ddl auto (create, create-drop, update, validate)
spring.jpa.hibernate.ddl-auto=create-drop
debug=true